#!/usr/bin/env python3
"""
resolve-install-plan.py

Runs on the HOST (Mac/Linux/WSL). Reads a bootstrap.json manifest, resolves
which payloads to install for a given device ABI and storage profile, and
emits a flat install-plan.txt that the host script (usb-push.sh) consumes.

Replaces resolve-install-plan.mjs — no node dependency required.

Usage:
  python3 resolve-install-plan.py <bootstrap.json> <device-abi> [storage-profile]
"""
import json, sys

def fatal(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)

if len(sys.argv) < 3:
    print("Usage: python3 resolve-install-plan.py <bootstrap.json> <device-abi> [storage-profile]", file=sys.stderr)
    sys.exit(64)

manifest_path = sys.argv[1]
device_abi = sys.argv[2]
requested_profile = sys.argv[3] if len(sys.argv) > 3 else None

try:
    with open(manifest_path) as f:
        manifest = json.load(f)
except Exception as e:
    fatal(f"cannot read {manifest_path}: {e}")

if manifest.get("schema_version") != "1.0":
    fatal(f'unsupported schema_version "{manifest.get("schema_version")}"')

supported_abis = manifest.get("compatibility", {}).get("supported_abis", [])
if device_abi not in supported_abis:
    fatal(f'device ABI "{device_abi}" not in supported ABIs [{", ".join(supported_abis)}]')

profile_id = requested_profile or manifest.get("defaults", {}).get("storage_profile")
if not profile_id:
    fatal("no storage profile specified and no default in manifest")

profiles = manifest.get("storage_profiles", [])
profile = next((p for p in profiles if p.get("id") == profile_id), None)
if not profile:
    available = ", ".join(p.get("id", "?") for p in profiles)
    fatal(f'storage profile "{profile_id}" not found (available: {available})')

keep_tags = set(profile.get("keep_tags", []))
drop_tags = set(profile.get("drop_tags", []))

def should_install(payload):
    abi = payload.get("abi", "any")
    if abi != "any" and abi != device_abi:
        return False
    if payload.get("required"):
        return True
    tags = payload.get("install_tags", [])
    if any(t in drop_tags for t in tags):
        return False
    return any(t in keep_tags for t in tags)

def action_for(payload):
    return "extract" if payload.get("path", "").endswith(".tar") else "copy"

selected = [p for p in manifest.get("payloads", []) if should_install(p)]
if not selected:
    fatal("no payloads selected -- check ABI and storage profile")

bundle = manifest.get("bundle", {})
defaults = manifest.get("defaults", {})

lines = [
    "# emergency-nomad install plan",
    "# generated by resolve-install-plan.py -- do not edit",
    f'# bundle={bundle.get("id")} version={bundle.get("version")} profile={profile_id} abi={device_abi}',
    "# format: ACTION SOURCE_PATH DEST_SUBDIR SHA256",
    "#",
]

count = 0
for p in selected:
    lines.append(f'{action_for(p)} {p["path"]} {p["kind"]} {p["sha256"]}')
    count += 1

for inp in manifest.get("upstream_inputs", []):
    lines.append(f'seed {inp["path"]} collections -')
    count += 1

lines.append(f'# config: loopback_base_url={defaults.get("loopback_base_url")}')
lines.append(f'# config: seed_network_policy={defaults.get("seed_network_policy")}')
lines.append(f'# config: oneshot_enabled={str(defaults.get("oneshot_enabled")).lower()}')
lines.append(f'# config: storage_profile={profile_id}')
lines.append(f'# config: bundle_id={bundle.get("id")}')
lines.append(f'# config: bundle_version={bundle.get("version")}')
lines.append(f'# config: installed_abi={device_abi}')
lines.append(f"# total_actions={count}")

print("\n".join(lines))
