# resolve-install-plan.ps1
# PowerShell version of the install plan resolver. No external dependencies.
param(
    [Parameter(Mandatory)][string]$ManifestPath,
    [Parameter(Mandatory)][string]$DeviceAbi,
    [string]$ProfileOverride
)

$ErrorActionPreference = "Stop"

$m = Get-Content $ManifestPath -Raw | ConvertFrom-Json

if ($m.schema_version -ne "1.0") {
    Write-Error "unsupported schema_version '$($m.schema_version)'"
    exit 1
}

$supported = @($m.compatibility.supported_abis)
if ($DeviceAbi -notin $supported) {
    Write-Error "device ABI '$DeviceAbi' not in [$($supported -join ', ')]"
    exit 1
}

$profileId = if ($ProfileOverride) { $ProfileOverride } else { $m.defaults.storage_profile }
if (-not $profileId) {
    Write-Error "no storage profile specified"
    exit 1
}

$profile = $m.storage_profiles | Where-Object { $_.id -eq $profileId }
if (-not $profile) {
    $avail = ($m.storage_profiles | ForEach-Object { $_.id }) -join ", "
    Write-Error "profile '$profileId' not found (available: $avail)"
    exit 1
}

$keepTags = [System.Collections.Generic.HashSet[string]]::new([string[]]@($profile.keep_tags))
$dropTags = [System.Collections.Generic.HashSet[string]]::new([string[]]@(if ($profile.drop_tags) { $profile.drop_tags } else { @() }))

function ShouldInstall($p) {
    if ($p.abi -ne "any" -and $p.abi -ne $DeviceAbi) { return $false }
    if ($p.required -eq $true) { return $true }
    $tags = @($p.install_tags)
    foreach ($t in $tags) { if ($dropTags.Contains($t)) { return $false } }
    foreach ($t in $tags) { if ($keepTags.Contains($t)) { return $true } }
    return $false
}

$selected = @($m.payloads | Where-Object { ShouldInstall $_ })
if ($selected.Count -eq 0) {
    Write-Error "no payloads selected"
    exit 1
}

$lines = @(
    "# emergency-nomad install plan"
    "# generated by resolve-install-plan.ps1 -- do not edit"
    "# bundle=$($m.bundle.id) version=$($m.bundle.version) profile=$profileId abi=$DeviceAbi"
    "# format: ACTION SOURCE_PATH DEST_SUBDIR SHA256"
    "#"
)

$count = 0
foreach ($p in $selected) {
    $action = if ($p.path -like "*.tar") { "extract" } else { "copy" }
    $lines += "$action $($p.path) $($p.kind) $($p.sha256)"
    $count++
}

foreach ($inp in $m.upstream_inputs) {
    $lines += "seed $($inp.path) collections -"
    $count++
}

$d = $m.defaults
$lines += "# config: loopback_base_url=$($d.loopback_base_url)"
$lines += "# config: seed_network_policy=$($d.seed_network_policy)"
$lines += "# config: oneshot_enabled=$("$($d.oneshot_enabled)".ToLower())"
$lines += "# config: storage_profile=$profileId"
$lines += "# config: bundle_id=$($m.bundle.id)"
$lines += "# config: bundle_version=$($m.bundle.version)"
$lines += "# config: installed_abi=$DeviceAbi"
$lines += "# total_actions=$count"

$lines -join "`n"
